version: "3.8"

volumes:
  postgres_data:
  static_data:
  media_data:

services:
  backend:
    build: ./backend
    container_name: magic-backend
    env_file: .env
    volumes:
      - static_data:/app/static
      - media_data:/app/media
      - ./backend/db.sqlite3:/app/db.sqlite3 
    ports:
      - 8000:8000
    restart: always
    command: sh -c "python3 manage.py makemigrations &&
                    python3 manage.py migrate &&
                    python3 manage.py collectstatic --noinput &&
                    gunicorn bigcorp.wsgi:application --bind 0.0.0.0:8000 &&
                    stripe listen --forward-to localhost:8000/payment/webhook-stripe/"

  redis:
    image: redis:7.2.3-alpine
    container_name: magic-redis
    restart: unless-stopped

  celery:
    build: ./backend
    container_name: magic-celery
    env_file: .env
    depends_on:
      - redis
    volumes:
      - static_data:/app/static
      - ./backend/db.sqlite3:/app/db.sqlite3
    restart: always
    command: celery -A bigcorp worker --loglevel=info --beat

  nginx:
    image: nginx:latest
    container_name: magic-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_data:/app/static
      - media_data:/app/media
    ports:
      - 80:80
    restart: always