# Generated by Django 4.2.4 on 2025-08-07 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productproxy',
            options={'verbose_name': 'Доступный продукт', 'verbose_name_plural': 'Доступные продукты'},
        ),
    ]
