# Generated by Django 4.2.4 on 2025-08-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cart_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
