name: Main Magic workflow

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"

jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "Hello, World!"
  
  run-unit-test:
    runs-on: ubuntu-latest
    needs: print-message
    strategy:
      matrix:
        backend-app: ['shop', 'otherapp', 'cart', 'account', 'api']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          cd backend/${{ matrix.backend-app }}
          pip install -r requirements.txt
      - name: Start test
        run: |
          cd backend/${{ matrix.backend-app }}
          python manage.py test

  send-message:
    runs-on: ubuntu-latest
    needs: [print-message, run-unit-test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get commit info
        id: commit
        run: |
          echo "MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT
          echo "AUTHOR=$(git log -1 --pretty=%an)" >> $GITHUB_OUTPUT
          echo "DATE=$(git log -1 --pretty=%cd --date=format:'%Y-%m-%d %H:%M')" >> $GITHUB_OUTPUT
      
      - name: Get branch name
        id: branch
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🚀 Deployment Successful 🚀

            -> Repository: ${{ github.repository }}
            -> Branch: ${{ steps.branch.outputs.BRANCH }}

            Commit:
            🔹 Author: ${{ steps.commit.outputs.AUTHOR }}
            🔹 Date: ${{ steps.commit.outputs.DATE }}
            🔹 Message: ${{ steps.commit.outputs.MESSAGE }}

            Workflow run -> [#${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          parse_mode: markdown